Repository heremaps/here-data-sdk-typescript, pull requests merged in 2020-01, with the labels that each got.

#134 Add NV pipeline for performance test
  .gitlab-ci.yml
Labels: ci

#139 Create Weekly_Verification pipeline for performance test
  .gitlab-ci.yml
Labels: ci

#140 Add perfomance tests to the NV and WK jobs
  .gitignore
  .gitlab-ci.yml
  @here/olp-sdk-dataservice-read/test/unit/ArtifactClient.test.ts
  scripts/linux/nv/gitlab_test_performance.sh
  scripts/linux/wv/gitlab_test_performance_extended.sh
  tests/performance/getDataMemoryTest.ts
  tests/performance/longMemoryTest.ts
  tests/performance/shortMemoryTest.ts
  tests/performance/utils.ts
  tests/utils/mocked-olp-server/README.md
  tests/utils/mocked-olp-server/base-urls.js
  tests/utils/mocked-olp-server/blob_service.js
  tests/utils/mocked-olp-server/config_service.js
  tests/utils/mocked-olp-server/errors_generator.js
  tests/utils/mocked-olp-server/lookup_service.js
  tests/utils/mocked-olp-server/metadata_service.js
  tests/utils/mocked-olp-server/query_service.js
  tests/utils/mocked-olp-server/server.js
  tests/utils/mocked-olp-server/urls.js
  tsconfig.json
  yarn.lock
Labels: ci, enhancement

#149 Fix typo in CI config for NV/WV jobs
  .gitlab-ci.yml
Labels: bug, ci

#152 Fix in performance script for nodejs,nvm,npx
  scripts/linux/nv/gitlab_test_performance.sh
  scripts/linux/wv/gitlab_test_performance_extended.sh
Labels: ci
