Repository heremaps/here-data-sdk-typescript, pull requests merged in 2020-08, with the labels that each got.

#348 Add verbose loglevel,fix report path
  .gitlab-ci.yml
Labels: ci

#347 Update documentation
  README.md
  docs/GettingStartedGuide.md
  docs/examples/nodejs-read-index-layer.md
  docs/examples/nodejs-read-stream-layer.md
  docs/examples/nodejs-read-versioned-layer.md
  docs/examples/nodejs-read-volatile-layer.md
Labels: merge-after-release-1.5.0

#354 Compile perfomance tests during the bootstrap.
  scripts/linux/wv/gitlab_test_performance_extended.sh
Labels: ci

#355 Up versions and add changelog.
  .travis.yml
  @here/olp-sdk-authentication/lib.version.ts
  @here/olp-sdk-authentication/lib/HttpError.ts
  @here/olp-sdk-authentication/package.json
  @here/olp-sdk-core/package.json
  @here/olp-sdk-dataservice-api/lib/HttpError.ts
  @here/olp-sdk-dataservice-api/lib/blob-api.ts
  @here/olp-sdk-dataservice-api/package.json
  @here/olp-sdk-dataservice-read/README.md
  @here/olp-sdk-dataservice-read/lib.version.ts
  @here/olp-sdk-dataservice-read/lib/DataStoreDownloadManager.ts
  @here/olp-sdk-dataservice-read/lib/DataStoreRequestBuilder.ts
  @here/olp-sdk-dataservice-read/lib/DownloadManager.ts
  @here/olp-sdk-dataservice-read/lib/HRN.ts
  @here/olp-sdk-dataservice-read/lib/cache/ApiCacheRepository.ts
  @here/olp-sdk-dataservice-read/lib/cache/KeyValueCache.ts
  @here/olp-sdk-dataservice-read/lib/cache/LRUCache.ts
  @here/olp-sdk-dataservice-read/lib/client/DataRequest.ts
  @here/olp-sdk-dataservice-read/lib/client/FetchOptions.ts
  @here/olp-sdk-dataservice-read/lib/client/OlpClientSettings.ts
  @here/olp-sdk-dataservice-read/lib/utils/QuadKeyUtils.ts
  @here/olp-sdk-dataservice-read/lib/utils/RequestBuilderFactory.ts
  @here/olp-sdk-dataservice-read/lib/utils/getDataSizeUtil.ts
  @here/olp-sdk-dataservice-read/lib/utils/getEnvLookupUrl.ts
  @here/olp-sdk-dataservice-read/lib/utils/getTile.ts
  @here/olp-sdk-dataservice-read/package.json
  @here/olp-sdk-dataservice-write/package.json
  @here/olp-sdk-fetch/package.json
  CHANGELOG.md
  package.json
  scripts/publish-packages.sh
Labels: ci

#356 Update publishing config.
  scripts/publish-packages.sh
Labels: ci

#357 Update README.md for dataservice-write.
  @here/olp-sdk-dataservice-write/README.md
Labels: documentation

#358 Add dataservice-api as a dep. for core
  @here/olp-sdk-authentication/package.json
  @here/olp-sdk-core/package.json
  @here/olp-sdk-dataservice-read/package.json
  @here/olp-sdk-dataservice-write/README.md
  @here/olp-sdk-dataservice-write/package.json
  CHANGELOG.md
  package.json
  scripts/publish-packages.sh
Labels: ci, documentation

#359 Update publish script.
  scripts/publish-packages.sh
Labels: ci

#360 Start http server before testing bundles
  .gitlab-ci.yml
Labels: ci

#362 Change test runners configs.
  @here/olp-sdk-authentication/package.json
  @here/olp-sdk-authentication/test/mocha.opts
  @here/olp-sdk-core/package.json
  @here/olp-sdk-core/test/mocha.opts
  @here/olp-sdk-dataservice-api/package.json
  @here/olp-sdk-dataservice-api/test/mocha.opts
  @here/olp-sdk-dataservice-read/package.json
  @here/olp-sdk-dataservice-read/test/mocha.opts
  @here/olp-sdk-dataservice-write/package.json
  @here/olp-sdk-dataservice-write/test/mocha.opts
  @here/olp-sdk-fetch/package.json
  @here/olp-sdk-fetch/test/mocha.opts
  package.json
  tests/functional/mocha.opts
  tests/integration/api-breaks/mocha.opts
  tests/integration/mocha.opts
Labels: ci

#363 [CI]Generate detailed regression test report
  .gitlab-ci.yml
Labels: ci
